package com.example.cst2335_finalproject.bbc;

/**
 * Stores article information to be displayed
 *
 * @author Jaewoo Kim
 */
public class BBC_Articles {
    /**
     * Stores id generated by database
     */
    private long id;
    private String title;
    private String description;
    private String link;
    private String date;

    /**
     * Construct an item with the given variables
     * @param id the Long which has id generated by database
     * @param title the String which has title
     * @param description the String which has description
     * @param link the String which has URL
     * @param date the String which has date
     */
    public BBC_Articles(long id, String title, String description, String link, String date) {
        this.id = id;
        this.title = title;
        this.date = date;
        this.description = description;
        this.link = link;
    }

    public BBC_Articles(String title, String description, String link, String date) {
        this(-1, title, description, link, date);
    }

    public long getId() {
        return id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDate() {
        return date;
    }

    public String getShortDate() {
        return date.split(" ")[1]+" "+date.split(" ")[2]+" "+date.split(" ")[3];
    }

    public String getDescription() {
        return description;
    }

    public String getLink() {
        return link;
    }

    public void setLink(String link) {
        this.link = link;
    }
}
